version: '3.8'

services:
  backend:
    build: 
      context: ./DensityReportingToolBackend
      dockerfile: Dockerfile
    ports:
      - "5013:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./DensityReportingToolBackend:/app/src:ro

  frontend:
    build:
      context: ./DensityReportingToolFrontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge