CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Clients" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Address" text,
        "PhoneNumber" text,
        "Email" text,
        CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "PersonalInfos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Email" text NOT NULL,
        "PhoneNumber" text NOT NULL,
        CONSTRAINT "PK_PersonalInfos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "ProctorTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" text NOT NULL,
        CONSTRAINT "PK_ProctorTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleTitle" text NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Jobs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ClientId" integer NOT NULL,
        "ProjectName" text NOT NULL,
        "SiteAddress" text NOT NULL,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        CONSTRAINT "PK_Jobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Jobs_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Contractors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PersonalInfoId" integer NOT NULL,
        "CompanyName" text NOT NULL,
        "ClientId" integer,
        CONSTRAINT "PK_Contractors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Contractors_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Contractors_PersonalInfos_PersonalInfoId" FOREIGN KEY ("PersonalInfoId") REFERENCES "PersonalInfos" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "GeoPacificEmployees" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PersonalInfoId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        "Password" text NOT NULL,
        CONSTRAINT "PK_GeoPacificEmployees" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_GeoPacificEmployees_PersonalInfos_PersonalInfoId" FOREIGN KEY ("PersonalInfoId") REFERENCES "PersonalInfos" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_GeoPacificEmployees_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "DistributionLists" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobId" integer NOT NULL,
        "Name" text NOT NULL,
        "Description" text,
        CONSTRAINT "PK_DistributionLists" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DistributionLists_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "JobSiteContacts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobId" integer NOT NULL,
        "PersonalInfoId" integer NOT NULL,
        "Area" text,
        "Company" text,
        "Role" text,
        "IsPrimary" boolean NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "Notes" text,
        "IsActive" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        CONSTRAINT "PK_JobSiteContacts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_JobSiteContacts_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobSiteContacts_PersonalInfos_PersonalInfoId" FOREIGN KEY ("PersonalInfoId") REFERENCES "PersonalInfos" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "LabTests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobId" integer NOT NULL,
        "MaterialType" text,
        "ImportLocation" text,
        "ReceiveDate" timestamp with time zone,
        CONSTRAINT "PK_LabTests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LabTests_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "SitePlans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobId" integer NOT NULL,
        "SitePlanUrl" text NOT NULL,
        CONSTRAINT "PK_SitePlans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SitePlans_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "JobContractors" (
        "JobId" integer NOT NULL,
        "ContractorId" integer NOT NULL,
        CONSTRAINT "PK_JobContractors" PRIMARY KEY ("JobId", "ContractorId"),
        CONSTRAINT "FK_JobContractors_Contractors_ContractorId" FOREIGN KEY ("ContractorId") REFERENCES "Contractors" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobContractors_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Comments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmployeeId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Details" text NOT NULL,
        CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comments_GeoPacificEmployees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "GeoPacificEmployees" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "JobProjectManagers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobId" integer NOT NULL,
        "EmployeeId" integer NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "EndDate" timestamp with time zone,
        "Notes" text,
        "IsActive" boolean NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedDate" timestamp with time zone,
        "GeoPacificEmployeeId" integer,
        CONSTRAINT "PK_JobProjectManagers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_JobProjectManagers_GeoPacificEmployees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "GeoPacificEmployees" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_JobProjectManagers_GeoPacificEmployees_GeoPacificEmployeeId" FOREIGN KEY ("GeoPacificEmployeeId") REFERENCES "GeoPacificEmployees" ("Id"),
        CONSTRAINT "FK_JobProjectManagers_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "DistributionMembers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DistributionListId" integer NOT NULL,
        "PersonalInfoId" integer NOT NULL,
        CONSTRAINT "PK_DistributionMembers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DistributionMembers_DistributionLists_DistributionListId" FOREIGN KEY ("DistributionListId") REFERENCES "DistributionLists" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DistributionMembers_PersonalInfos_PersonalInfoId" FOREIGN KEY ("PersonalInfoId") REFERENCES "PersonalInfos" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Reports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobId" integer NOT NULL,
        "EmployeeId" integer NOT NULL,
        "ReviewerId" integer NOT NULL,
        "ReportNumber" integer NOT NULL,
        "StartDate" timestamp with time zone,
        "SubmitDate" timestamp with time zone,
        "DistributeDate" timestamp with time zone,
        "DistributionListId" integer,
        CONSTRAINT "PK_Reports" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reports_DistributionLists_DistributionListId" FOREIGN KEY ("DistributionListId") REFERENCES "DistributionLists" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Reports_GeoPacificEmployees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "GeoPacificEmployees" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reports_GeoPacificEmployees_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "GeoPacificEmployees" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reports_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Sieves" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LabTestId" integer NOT NULL,
        "TotalDryMassGrams" double precision,
        "MoistureContentBefore" double precision,
        "MoistureContentAfter" double precision,
        CONSTRAINT "PK_Sieves" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sieves_LabTests_LabTestId" FOREIGN KEY ("LabTestId") REFERENCES "LabTests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "JobNotes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CommentId" integer NOT NULL,
        "JobId" integer NOT NULL,
        CONSTRAINT "PK_JobNotes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_JobNotes_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_JobNotes_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "ReportMemos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReportId" integer NOT NULL,
        "Purpose" text,
        "CommentsAndObservations" text,
        "Conclusion" text,
        "CreatedDate" timestamp with time zone,
        "UpdatedDate" timestamp with time zone,
        CONSTRAINT "PK_ReportMemos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReportMemos_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "ReportPhotos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReportId" integer NOT NULL,
        "Code" text,
        "Url" text,
        "Description" text,
        "Latitude" double precision,
        "Longitude" double precision,
        "GpsAccuracyMeters" double precision,
        CONSTRAINT "PK_ReportPhotos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ReportPhotos_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "Proctors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProctorID" text,
        "LabTestId" integer NOT NULL,
        "SieveId" integer,
        "ProctorTypeId" integer NOT NULL,
        "MaxDensity" double precision,
        "CorrectedDensity" double precision,
        "OptimumMoistureContent" double precision,
        "SpecificGravity" double precision,
        CONSTRAINT "PK_Proctors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Proctors_LabTests_LabTestId" FOREIGN KEY ("LabTestId") REFERENCES "LabTests" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Proctors_ProctorTypes_ProctorTypeId" FOREIGN KEY ("ProctorTypeId") REFERENCES "ProctorTypes" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Proctors_Sieves_SieveId" FOREIGN KEY ("SieveId") REFERENCES "Sieves" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "SieveResults" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SieveId" integer NOT NULL,
        "SieveSize" integer NOT NULL,
        "GramsRetained" double precision NOT NULL,
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_SieveResults" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SieveResults_Sieves_SieveId" FOREIGN KEY ("SieveId") REFERENCES "Sieves" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "MemoComments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CommentId" integer NOT NULL,
        "MemoId" integer NOT NULL,
        CONSTRAINT "PK_MemoComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MemoComments_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MemoComments_ReportMemos_MemoId" FOREIGN KEY ("MemoId") REFERENCES "ReportMemos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "DensityTests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProctorId" integer NOT NULL,
        "ReportId" integer NOT NULL,
        "TestArea" text,
        "Location" text,
        "ElevationReference" integer,
        "ElevationValue" double precision,
        "ElevationUnit" integer,
        "CorrectedOversizePercentage" real,
        "ProbeDepth" integer,
        "ProbeDepthUnit" integer,
        "CompactionSpecification" double precision,
        "CompactionSpecificationUnit" integer,
        "DensityValue" double precision,
        "MoistureValue" double precision,
        "CreatedDate" timestamp with time zone DEFAULT (timezone('utc', now())),
        "LastEditDate" timestamp with time zone,
        CONSTRAINT "PK_DensityTests" PRIMARY KEY ("Id"),
        CONSTRAINT ck_densitytest_compactionspec_0_110 CHECK ("CompactionSpecification" IS NULL OR ("CompactionSpecification" >= 0 AND "CompactionSpecification" <= 110)),
        CONSTRAINT ck_densitytest_moisture_0_100 CHECK ("MoistureValue" IS NULL OR ("MoistureValue" >= 0 AND "MoistureValue" <= 100)),
        CONSTRAINT ck_densitytest_oversize_0_100 CHECK ("CorrectedOversizePercentage" IS NULL OR ("CorrectedOversizePercentage" >= 0 AND "CorrectedOversizePercentage" <= 100)),
        CONSTRAINT "FK_DensityTests_Proctors_ProctorId" FOREIGN KEY ("ProctorId") REFERENCES "Proctors" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DensityTests_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES "Reports" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "ProctorAdditionalJobs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProctorId" integer NOT NULL,
        "JobId" integer NOT NULL,
        CONSTRAINT "PK_ProctorAdditionalJobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProctorAdditionalJobs_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProctorAdditionalJobs_Proctors_ProctorId" FOREIGN KEY ("ProctorId") REFERENCES "Proctors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "DensityTestComments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CommentId" integer NOT NULL,
        "DensityTestId" integer NOT NULL,
        CONSTRAINT "PK_DensityTestComments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DensityTestComments_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DensityTestComments_DensityTests_DensityTestId" FOREIGN KEY ("DensityTestId") REFERENCES "DensityTests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE TABLE "ShotPlacements" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SitePlanId" integer NOT NULL,
        "DensityTestId" integer,
        "XCoordinate" double precision NOT NULL,
        "YCoordinate" double precision NOT NULL,
        CONSTRAINT "PK_ShotPlacements" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShotPlacements_DensityTests_DensityTestId" FOREIGN KEY ("DensityTestId") REFERENCES "DensityTests" ("Id"),
        CONSTRAINT "FK_ShotPlacements_SitePlans_SitePlanId" FOREIGN KEY ("SitePlanId") REFERENCES "SitePlans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Comments_EmployeeId" ON "Comments" ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Contractors_ClientId" ON "Contractors" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Contractors_PersonalInfoId" ON "Contractors" ("PersonalInfoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_DensityTestComments_CommentId" ON "DensityTestComments" ("CommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_DensityTestComments_DensityTestId" ON "DensityTestComments" ("DensityTestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_DensityTests_ProctorId" ON "DensityTests" ("ProctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_DensityTests_ReportId" ON "DensityTests" ("ReportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_DistributionLists_JobId" ON "DistributionLists" ("JobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_DistributionMembers_DistributionListId" ON "DistributionMembers" ("DistributionListId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_DistributionMembers_PersonalInfoId" ON "DistributionMembers" ("PersonalInfoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_GeoPacificEmployees_PersonalInfoId" ON "GeoPacificEmployees" ("PersonalInfoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_GeoPacificEmployees_RoleId" ON "GeoPacificEmployees" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_JobContractors_ContractorId" ON "JobContractors" ("ContractorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_JobNotes_CommentId" ON "JobNotes" ("CommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_JobNotes_JobId" ON "JobNotes" ("JobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_JobProjectManagers_EmployeeId" ON "JobProjectManagers" ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_JobProjectManagers_GeoPacificEmployeeId" ON "JobProjectManagers" ("GeoPacificEmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_JobProjectManagers_JobId" ON "JobProjectManagers" ("JobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Jobs_ClientId" ON "Jobs" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_JobSiteContacts_JobId_IsPrimary_IsActive" ON "JobSiteContacts" ("JobId", "IsPrimary", "IsActive") WHERE "IsPrimary" = true AND "IsActive" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_JobSiteContacts_PersonalInfoId" ON "JobSiteContacts" ("PersonalInfoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_LabTests_JobId" ON "LabTests" ("JobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_MemoComments_CommentId" ON "MemoComments" ("CommentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_MemoComments_MemoId" ON "MemoComments" ("MemoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_ProctorAdditionalJobs_JobId" ON "ProctorAdditionalJobs" ("JobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_ProctorAdditionalJobs_ProctorId" ON "ProctorAdditionalJobs" ("ProctorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Proctors_LabTestId" ON "Proctors" ("LabTestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Proctors_ProctorTypeId" ON "Proctors" ("ProctorTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Proctors_SieveId" ON "Proctors" ("SieveId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_ReportMemos_ReportId" ON "ReportMemos" ("ReportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_ReportPhotos_ReportId" ON "ReportPhotos" ("ReportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Reports_DistributionListId" ON "Reports" ("DistributionListId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Reports_EmployeeId" ON "Reports" ("EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Reports_JobId" ON "Reports" ("JobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Reports_ReviewerId" ON "Reports" ("ReviewerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ShotPlacements_DensityTestId" ON "ShotPlacements" ("DensityTestId") WHERE "DensityTestId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_ShotPlacements_SitePlanId" ON "ShotPlacements" ("SitePlanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_SieveResults_SieveId" ON "SieveResults" ("SieveId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_Sieves_LabTestId" ON "Sieves" ("LabTestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    CREATE INDEX "IX_SitePlans_JobId" ON "SitePlans" ("JobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250822190006_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250822190006_InitialCreate', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobNotes" DROP CONSTRAINT "FK_JobNotes_Comments_CommentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobProjectManagers" DROP CONSTRAINT "FK_JobProjectManagers_GeoPacificEmployees_EmployeeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "Jobs" DROP CONSTRAINT "FK_Jobs_Clients_ClientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    DROP TABLE "JobContractors";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    DROP TABLE "Contractors";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    DROP TABLE "Clients";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    DROP INDEX "IX_Jobs_ClientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobSiteContacts" DROP COLUMN "EndDate";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobSiteContacts" DROP COLUMN "StartDate";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "Jobs" DROP COLUMN "ClientId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobProjectManagers" RENAME COLUMN "EmployeeId" TO "PersonalInfoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER INDEX "IX_JobProjectManagers_EmployeeId" RENAME TO "IX_JobProjectManagers_PersonalInfoId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "PersonalInfos" ADD "Company" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "Jobs" ADD "ClientName" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "Jobs" ADD "JobNumber" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobNotes" ALTER COLUMN "CommentId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobNotes" ADD "CreatedDate" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobNotes" ADD "Note" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobNotes" ADD CONSTRAINT "FK_JobNotes_Comments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "Comments" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    ALTER TABLE "JobProjectManagers" ADD CONSTRAINT "FK_JobProjectManagers_PersonalInfos_PersonalInfoId" FOREIGN KEY ("PersonalInfoId") REFERENCES "PersonalInfos" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250903202147_InitialCreateWithUpdatedModels') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250903202147_InitialCreateWithUpdatedModels', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200200_AddProctorAdditionalFields') THEN
    ALTER TABLE "Proctors" ADD "DateSampled" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200200_AddProctorAdditionalFields') THEN
    ALTER TABLE "Proctors" ADD "DateTested" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200200_AddProctorAdditionalFields') THEN
    ALTER TABLE "Proctors" ADD "LabLocation" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200200_AddProctorAdditionalFields') THEN
    ALTER TABLE "Proctors" ADD "MaterialType" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200200_AddProctorAdditionalFields') THEN
    ALTER TABLE "Proctors" ADD "OversizePercentage" double precision;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200200_AddProctorAdditionalFields') THEN
    ALTER TABLE "Proctors" ADD "ProctorTestNumber" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250917200200_AddProctorAdditionalFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250917200200_AddProctorAdditionalFields', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919030716_UpdateReportToUsePersonalInfo') THEN
    ALTER TABLE "Reports" DROP CONSTRAINT "FK_Reports_GeoPacificEmployees_EmployeeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919030716_UpdateReportToUsePersonalInfo') THEN
    ALTER TABLE "Reports" DROP CONSTRAINT "FK_Reports_GeoPacificEmployees_ReviewerId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919030716_UpdateReportToUsePersonalInfo') THEN
    ALTER TABLE "Reports" ALTER COLUMN "ReviewerId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919030716_UpdateReportToUsePersonalInfo') THEN
    ALTER TABLE "Reports" ADD CONSTRAINT "FK_Reports_PersonalInfos_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "PersonalInfos" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919030716_UpdateReportToUsePersonalInfo') THEN
    ALTER TABLE "Reports" ADD CONSTRAINT "FK_Reports_PersonalInfos_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "PersonalInfos" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250919030716_UpdateReportToUsePersonalInfo') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250919030716_UpdateReportToUsePersonalInfo', '9.0.8');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102215615_AddIsPrimaryToJobProjectManager') THEN
    DROP INDEX "IX_JobProjectManagers_JobId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102215615_AddIsPrimaryToJobProjectManager') THEN
    ALTER TABLE "JobProjectManagers" ADD "IsPrimary" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102215615_AddIsPrimaryToJobProjectManager') THEN
    CREATE UNIQUE INDEX "IX_JobProjectManagers_JobId_IsPrimary_IsActive" ON "JobProjectManagers" ("JobId", "IsPrimary", "IsActive") WHERE "IsPrimary" = true AND "IsActive" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102215615_AddIsPrimaryToJobProjectManager') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251102215615_AddIsPrimaryToJobProjectManager', '9.0.8');
    END IF;
END $EF$;
COMMIT;

