services:
  - type: web
    name: density-reporting-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: DB_HOST
        value: ep-purple-art-aa9fvlr7-pooler.westus3.azure.neon.tech
      - key: DB_NAME
        value: DensityReportingTool
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_ygUF4x0pNEbX
      - key: DB_SSLMODE
        value: require
      - key: DB_CHANNELBINDING
        value: require
