// <auto-generated />
using System;
using DensityReportingToolBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DensityReportingToolBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DensityReportingToolBackend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DetailsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DensityTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CompactionSpecification")
                        .HasColumnType("double precision");

                    b.Property<int?>("CompactionSpecificationUnit")
                        .HasColumnType("integer");

                    b.Property<float?>("CorrectedOversizePercentage")
                        .HasColumnType("real");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<double?>("DensityValue")
                        .HasColumnType("double precision");

                    b.Property<int?>("ElevationReference")
                        .HasColumnType("integer");

                    b.Property<int?>("ElevationUnit")
                        .HasColumnType("integer");

                    b.Property<double?>("ElevationValue")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastEditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<double?>("MoistureValue")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProbeDepth")
                        .HasColumnType("integer");

                    b.Property<int?>("ProbeDepthUnit")
                        .HasColumnType("integer");

                    b.Property<int>("ProctorId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("TestArea")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProctorId");

                    b.HasIndex("ReportId");

                    b.ToTable("DensityTests", t =>
                        {
                            t.HasCheckConstraint("ck_densitytest_compactionspec_0_110", "\"CompactionSpecification\" IS NULL OR (\"CompactionSpecification\" >= 0 AND \"CompactionSpecification\" <= 110)");

                            t.HasCheckConstraint("ck_densitytest_moisture_0_100", "\"MoistureValue\" IS NULL OR (\"MoistureValue\" >= 0 AND \"MoistureValue\" <= 100)");

                            t.HasCheckConstraint("ck_densitytest_oversize_0_100", "\"CorrectedOversizePercentage\" IS NULL OR (\"CorrectedOversizePercentage\" >= 0 AND \"CorrectedOversizePercentage\" <= 100)");
                        });
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DensityTestComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("DensityTestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("DensityTestId");

                    b.ToTable("DensityTestComments");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DistributionList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("DistributionLists");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DistributionMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistributionListId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistributionListId");

                    b.HasIndex("PersonalInfoId");

                    b.ToTable("DistributionMembers");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobContractor", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("ContractorId")
                        .HasColumnType("integer");

                    b.HasKey("JobId", "ContractorId");

                    b.HasIndex("ContractorId");

                    b.ToTable("JobContractors");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("JobId");

                    b.ToTable("JobNotes");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobProjectManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JobId");

                    b.ToTable("JobProjectManagers");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobSiteContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PersonalInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonalInfoId");

                    b.HasIndex("JobId", "IsPrimary", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = true AND \"IsActive\" = true");

                    b.ToTable("JobSiteContacts");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImportLocation")
                        .HasColumnType("text");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.MemoComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<int>("MemoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("MemoId");

                    b.ToTable("MemoComments");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.PersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PersonalInfos", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Proctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CorrectedDensity")
                        .HasColumnType("double precision");

                    b.Property<int>("LabTestId")
                        .HasColumnType("integer");

                    b.Property<double?>("MaxDensity")
                        .HasColumnType("double precision");

                    b.Property<double?>("OptimumMoistureContent")
                        .HasColumnType("double precision");

                    b.Property<string>("ProctorID")
                        .HasColumnType("text");

                    b.Property<int>("ProctorTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SieveId")
                        .HasColumnType("integer");

                    b.Property<double?>("SpecificGravity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("ProctorTypeId");

                    b.HasIndex("SieveId");

                    b.ToTable("Proctors");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ProctorAdditionalJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("ProctorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ProctorId");

                    b.ToTable("ProctorAdditionalJobs");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ProctorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProctorTypes");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DistributeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DistributionListId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistributionListId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("JobId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ReportMemo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentsAndObservations")
                        .HasColumnType("text");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportMemos");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ReportPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double?>("GpsAccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportPhotos");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ShotPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DensityTestId")
                        .HasColumnType("integer");

                    b.Property<int>("SitePlanId")
                        .HasColumnType("integer");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("double precision");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DensityTestId")
                        .IsUnique()
                        .HasFilter("\"DensityTestId\" IS NOT NULL");

                    b.HasIndex("SitePlanId");

                    b.ToTable("ShotPlacements");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Sieve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LabTestId")
                        .HasColumnType("integer");

                    b.Property<double?>("MoistureContentAfter")
                        .HasColumnType("double precision");

                    b.Property<double?>("MoistureContentBefore")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalDryMassGrams")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.ToTable("Sieves");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.SieveResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("GramsRetained")
                        .HasColumnType("double precision");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SieveId")
                        .HasColumnType("integer");

                    b.Property<int>("SieveSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SieveId");

                    b.ToTable("SieveResults");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.SitePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<string>("SitePlanUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("SitePlans");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.GeoPacificEmployee", b =>
                {
                    b.HasBaseType("DensityReportingToolBackend.Models.PersonalInfo");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasIndex("RoleId");

                    b.ToTable("GeoPacificEmployees", (string)null);
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Comment", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.GeoPacificEmployee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Contractor", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.PersonalInfo", "Details")
                        .WithMany()
                        .HasForeignKey("DetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Details");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DensityTest", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Proctor", "Proctor")
                        .WithMany("DensityTests")
                        .HasForeignKey("ProctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Report", "Report")
                        .WithMany("DensityTests")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proctor");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DensityTestComment", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Comment", "Comment")
                        .WithMany("DensityTestComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.DensityTest", "DensityTest")
                        .WithMany("Comments")
                        .HasForeignKey("DensityTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("DensityTest");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DistributionList", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("DistributionLists")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DistributionMember", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.DistributionList", "DistributionList")
                        .WithMany("DistributionMembers")
                        .HasForeignKey("DistributionListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DistributionList");

                    b.Navigation("PersonalInfo");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobContractor", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Contractor", "Contractor")
                        .WithMany("JobContracts")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("JobContracts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobNote", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Comment", "Comment")
                        .WithMany("JobNotes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("JobNotes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobProjectManager", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.GeoPacificEmployee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("ProjectManagers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.JobSiteContact", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("SiteContacts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.PersonalInfo", "PersonalInfo")
                        .WithMany()
                        .HasForeignKey("PersonalInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("PersonalInfo");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.LabTest", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("LabTests")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.MemoComment", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Comment", "Comment")
                        .WithMany("MemoComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.ReportMemo", "Memo")
                        .WithMany("Comments")
                        .HasForeignKey("MemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Memo");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Proctor", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.LabTest", "LabTest")
                        .WithMany("Proctors")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.ProctorType", "ProctorType")
                        .WithMany("Proctors")
                        .HasForeignKey("ProctorTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Sieve", "Sieve")
                        .WithMany("Proctors")
                        .HasForeignKey("SieveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LabTest");

                    b.Navigation("ProctorType");

                    b.Navigation("Sieve");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ProctorAdditionalJob", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("ProctorAdditionalJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Proctor", "Proctor")
                        .WithMany("AdditionalJobs")
                        .HasForeignKey("ProctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Proctor");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Report", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.DistributionList", "DistributionList")
                        .WithMany()
                        .HasForeignKey("DistributionListId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DensityReportingToolBackend.Models.GeoPacificEmployee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("Reports")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.GeoPacificEmployee", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionList");

                    b.Navigation("Employee");

                    b.Navigation("Job");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ReportMemo", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Report", "Report")
                        .WithMany("Memos")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ReportPhoto", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Report", "Report")
                        .WithMany("Photos")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ShotPlacement", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.DensityTest", "DensityTest")
                        .WithOne("ShotPlacement")
                        .HasForeignKey("DensityReportingToolBackend.Models.ShotPlacement", "DensityTestId");

                    b.HasOne("DensityReportingToolBackend.Models.SitePlan", "SitePlan")
                        .WithMany("ShotPlacements")
                        .HasForeignKey("SitePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DensityTest");

                    b.Navigation("SitePlan");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Sieve", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.LabTest", "LabTest")
                        .WithMany("Sieves")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.SieveResult", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Sieve", "Sieve")
                        .WithMany("Results")
                        .HasForeignKey("SieveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sieve");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.SitePlan", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.Job", "Job")
                        .WithMany("SitePlans")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.GeoPacificEmployee", b =>
                {
                    b.HasOne("DensityReportingToolBackend.Models.PersonalInfo", null)
                        .WithOne()
                        .HasForeignKey("DensityReportingToolBackend.Models.GeoPacificEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DensityReportingToolBackend.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Comment", b =>
                {
                    b.Navigation("DensityTestComments");

                    b.Navigation("JobNotes");

                    b.Navigation("MemoComments");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Contractor", b =>
                {
                    b.Navigation("JobContracts");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DensityTest", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ShotPlacement");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.DistributionList", b =>
                {
                    b.Navigation("DistributionMembers");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Job", b =>
                {
                    b.Navigation("DistributionLists");

                    b.Navigation("JobContracts");

                    b.Navigation("JobNotes");

                    b.Navigation("LabTests");

                    b.Navigation("ProctorAdditionalJobs");

                    b.Navigation("ProjectManagers");

                    b.Navigation("Reports");

                    b.Navigation("SiteContacts");

                    b.Navigation("SitePlans");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.LabTest", b =>
                {
                    b.Navigation("Proctors");

                    b.Navigation("Sieves");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Proctor", b =>
                {
                    b.Navigation("AdditionalJobs");

                    b.Navigation("DensityTests");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ProctorType", b =>
                {
                    b.Navigation("Proctors");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Report", b =>
                {
                    b.Navigation("DensityTests");

                    b.Navigation("Memos");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.ReportMemo", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.Sieve", b =>
                {
                    b.Navigation("Proctors");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("DensityReportingToolBackend.Models.SitePlan", b =>
                {
                    b.Navigation("ShotPlacements");
                });
#pragma warning restore 612, 618
        }
    }
}
